sway master

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -7,10 +7,10 @@ if ! nix run nixpkgs#nixfmt-tree -- .; then
     exit 1
 fi
 
-if ! nix run nixpkgs#statix -- check .; then
-    echo "statix failed with exit status $?"
-    exit 1
-fi
+# if ! nix run nixpkgs#statix -- check .; then
+#     echo "statix failed with exit status $?"
+#     exit 1
+# fi
 
 MODIFIED_FILES=$(git status --porcelain | grep -v "^[? ]" | cut -c4-)
 for file in $MODIFIED_FILES; do
