fix

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
 if ! ( nix run nixpkgs#nixfmt-tree -- . && nix run nixpkgs#statix -- check . ) ; then
-	echo "pre-push hook failed with exit status $?"
+	echo "pre-commit hook failed with exit status $?"
 	exit 1
 fi
